# Generated by Django 5.2 on 2025-04-07 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appUsuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name_plural': 'Usuario'},
        ),
    ]
